// Generated by CoffeeScript 1.12.6
(function() {
  var conf;

  conf = {
    id: null,
    secret: null,
    encrpyt_key: null,
    mch_id: null,
    download: null,
    test_temp: []
  };

  if (conf.id === null || conf.secret === null) {
    throw Error('id and secret is require');
  }

  module.exports = conf;

}).call(this);

//# sourceMappingURL=config.js.map
