// Generated by CoffeeScript 1.10.0
(function() {
  var conf;

  conf = {
    id: 'wx481c10d59e2815b9',
    secret: 'f4da79269d88c47b2040387e44882eda',
    encrpyt_key: 'GVOBHZZ1A3RRULTV71QF8ZNEQLU8153O',
    mch_id: '1340517601',
    download: null,
    test_temp: []
  };

  if (conf.id === null || conf.secret === null) {
    throw Error('id and secret is require');
  }

  module.exports = conf;

}).call(this);

//# sourceMappingURL=config.js.map
