// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, arr, conf, f, testing_func, wx, wxp;

  wxp = require('../');

  conf = require('./config');

  Promise = require('bluebird');

  wx = new wxp.Wx(conf.id, conf.secret, conf.encrpyt_key, null, conf.mch_id);

  testing_func = null;

  arr = [
    function() {
      testing_func = 'Access Token';
      return wx.access_token().then(function(token) {
        return console.log("Test Access Token Success, Token: " + token);
      });
    }, function() {
      testing_func = 'JS API Ticket';
      return wx.jsapi_ticket().then(function(ticket) {
        return console.log("Test JS API Ticket Success, Ticket: " + ticket);
      });
    }
  ];

  if (conf.test_temp.length) {
    f = function() {
      testing_func = '模板信息';
      return wx.temp_info(conf.test_temp[0], conf.test_temp[1], conf.test_temp[2], conf.test_temp[3]);
    };
    arr.push(f);
  }

  if (conf.download) {
    f = function() {
      testing_func = '媒体下载';
      return wx.download(conf.download);
    };
    arr.push(f);
  }

  Promise.mapSeries(arr, function(p) {
    return Promise.resolve(p());
  }).then(function() {
    return console.log('100% Success');
  })["catch"](function(err) {
    console.log(testing_func + "发生错误");
    return console.log(err.stack);
  })["finally"](function() {
    return console.log('Test Complete');
  });

}).call(this);

//# sourceMappingURL=run.js.map
