// Generated by CoffeeScript 1.10.0
(function() {
  var Cache, Promise;

  Promise = require('bluebird');

  Cache = (function() {
    function Cache() {}

    Cache.prototype.get = function(key) {
      return Promise.resolve(null);
    };

    Cache.prototype.set = function(key, value, expire) {
      return Promise.resolve(value);
    };

    return Cache;

  })();

  module.exports = Cache;

}).call(this);

//# sourceMappingURL=cache.js.map
