// Generated by CoffeeScript 1.10.0
(function() {
  var WxError, WxHttpError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  WxHttpError = (function(superClass) {
    extend(WxHttpError, superClass);

    function WxHttpError(msg) {
      this.name = 'HttpError';
      this.msg = msg;
    }

    WxHttpError.prototype.toString = function() {
      return this.name + ": " + this.msg;
    };

    return WxHttpError;

  })(Error);

  WxError = (function(superClass) {
    extend(WxError, superClass);

    function WxError(msg) {
      this.name = 'WxError';
      this.msg = msg;
    }

    return WxError;

  })(WxHttpError);

  module.exports.WxHttpError = WxHttpError;

  module.exports.WxError = WxError;

}).call(this);

//# sourceMappingURL=errorHandler.js.map
