// Generated by CoffeeScript 1.10.0
(function() {
  var errorHandler;

  errorHandler = require('./errorHandler');

  module.exports = {
    Wx: require('./wx'),
    wxQy: require('./wxqy'),
    WxHttpError: errorHandler.WxHttpError,
    WxError: errorHandler.WxError
  };

}).call(this);

//# sourceMappingURL=index.js.map
